### PR TITLE
Added Doc getOpt

### PR DESCRIPTION
**Pull request by Ugon**
I forgot about adding a corresponding getter xD And i also like the fold version for put more as well.

### CODE REVIEW

**Comment by ghik** [comment]
For consistency, `getOpt` for `Option` should also be rewritten to `fold`

**Comment by Ugon** [comment]
Did you mean `putOpt`?
Also could you publish a new version with those changes?

**Comment by ghik** [comment]
Yep, obviously I meant `putOpt`.

**Comment by ghik** [comment]
I will wait a bit for https://github.com/AVSystem/scala-commons/pull/29 to get finished and publish new version.

**Pull request merged**
