### PR TITLE
Fix Redis tests by with new, valid certificate

### PR DESCRIPTION
**Pull request by halotukozak**

### CODE REVIEW

**Review by sebaciv — APPROVED** [review]

**Comment by ddworak** [comment]
@halotukozak why do we need this so quickly after https://github.com/AVSystem/scala-commons/pull/594? The certificates added there had a long expiration date.

**Comment by halotukozak** [comment]
> @halotukozak why do we need this so quickly after #594? The certificates added there had a long expiration date.

I have no idea ¯\_(ツ)_/¯. I've found the solution, but not the explanation.

**Comment by ddworak** [comment]
Please file an issue with all the details as the tests were passing before your change and it's not obvious. We will have to look into it to prevent it from reoccurring.

**Comment by halotukozak** [comment]
> Please file an issue with all the details as the tests were passing before your change and it's not obvious. We will have to look into it to prevent it from reoccurring.

Done #607

**Pull request merged**
